env:
  browser: true
  commonjs: true
  es2021: true
ignorePatterns:
  - public
  - views
  - node_modules
  - .yarn
  - .idea
  - yarn.lock
  - package-lock.json
  - README.md
  - CHANGELOG.md
  - .yarnrc
  - .gitignore
  - .prettierrc.json
  - .prettierignore
  - prototypes
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules:
  for-direction: error
  getter-return: error
  no-async-promise-executor: error
  no-compare-neg-zero: error
  no-cond-assign: error
  no-console: off
  no-constant-condition: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-else-if: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-dupe-class-members: error
  no-duplicate-imports: error
  no-multi-spaces: warn
  no-alert: error
  no-await-in-loop: off
  no-empty: error
  no-empty-character-class: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-parens: error
  no-extra-semi: error
  no-func-assign: error
  no-import-assign: error
  no-inner-declarations: error
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-loss-of-precision: error
  no-misleading-character-class: error
  no-obj-calls: error
  no-promise-executor-return: error
  no-prototype-builtins: error
  no-regex-spaces: warn
  no-setter-return: off
  no-sparse-arrays: error
  no-template-curly-in-string: error
  no-unexpected-multiline: warn
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  use-isnan: warn
  valid-typeof: warn
  accessor-pairs: warn
  array-callback-return: off
  block-scoped-var: error
  class-methods-use-this: off
  complexity:
    - error
    - 2
  consistent-return: warn
  constructor-super: warn
  no-array-constructor: warn
  consistent-this: warn
  no-buffer-constructor: off
  semi:
    - error
    - always
